### ISSUE TITLE
Social Plugin Deactitaved

### ISSUE THREAD

**Issue by maybenikhil** [ExpressLRS/Docs#377]
restore with:
```
INHERIT: mkdocs.yml

# these will throw a warning but exist to inject privacy and license links post build to footer
privacy_policy_page_path: "info/privacy-policy"
licenses_page_path: "info/licenses"
terms_and_conditions_page_path: "info/terms-and-conditions"

theme:
  features:
    - navigation.path
    - announce.dismiss
    - navigation.sections
    - navigation.tabs
    - navigation.footer
    - search.highlight
    - search.suggest
    - toc.follow

plugins:
  social:
    cards_layout: default/accent
    cards_layout_options:
      background_color: "#00000000"
      background_image: layouts/social.png
      font_family: Open Sans
  git-committers:
    enabled: !ENV [CI, false]
    repository: ExpressLRS/Docs
    branch: master
  optimize:
    enabled: !ENV [CI, false]
```

blocked by https://github.com/squidfunk/mkdocs-material/issues/6983
